batch_size: 32
config_type: top5_zc_ensemble
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: class_scene
optimizer: bananas
out_dir: run
predictor: zc
search:
  acq_fn_optimization: random_sampling
  acq_fn_type: its
  checkpoint_freq: 200
  encoding_type: path
  epochs: 200
  k: 10
  max_mutations: 1
  num_arches_to_mutate: 2
  num_candidates: 100
  num_ensemble: 1
  num_init: 10
  predictor_type: xgb
  seed: 9004
  zc_ensemble: true
  zc_names:
  - fisher
  - jacov
  - grasp
  - flops
  - plain
  zc_only: false
search_space: transbench101_macro
seed: 9004
test_size: 200
train_portion: 0.7
