batch_size: 32
config_type: correlation
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: autoencoder
out_dir: run
predictor: l2_norm
search_space: transbench101_macro
seed: 9005
test_size: 200
train_portion: 0.7
